FROM postgres:15.4
RUN apt -y update
RUN apt -y install postgresql-15-cron postgresql-15-partman
#RUN apt -y install postgresql-15-powa
#RUN apt -y install postgresql-15-pg-qualstats
#RUN apt -y install postgresql-15-pg-stat-kcache
#RUN apt -y install postgresql-15-hypopg