services:
  postgres:
    container_name: utro-postgres
    build:
      dockerfile: ./docker/postgres/Dockerfile
    command: [
      "postgres",
      "-c", "log_destination=stderr",
      "-c", "shared_preload_libraries=pg_cron",
      "-c", "wal_level=logical",
      "-c", "max_wal_senders=10",
      "-c", "max_replication_slots=10",
      "-c", "cron.database_name=data_gateway",
    ]
    ports:
      - "5432:5432"
    restart: always
    shm_size: 4g
    volumes:
      - ./docker/postgres/initdb.d:/docker-entrypoint-initdb.d:ro
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 1s
      retries: 10
  pgadmin:
    container_name: utro-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.net
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - default
    volumes:
      - pgadmin_data:/var/lib/pgadmin
networks:
  default:
    name: utro
    driver: bridge
    external: false
volumes:
  postgres_data:
  pgadmin_data: