CREATE DATABASE utro;

\c utro;


-- CREATE DATABASE lkp;
-- CREATE DATABASE sms;
-- \c merlin;
-- CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
-- CREATE EXTENSION IF NOT EXISTS hypopg;

-- CREATE DATABASE powa ;
-- \c powa
-- CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
-- CREATE EXTENSION IF NOT EXISTS btree_gist;
-- CREATE EXTENSION IF NOT EXISTS powa;
-- CREATE EXTENSION IF NOT EXISTS pg_qualstats;
-- CREATE EXTENSION IF NOT EXISTS pg_stat_kcache;

-- CREATE ROLE powa SUPERUSER LOGIN PASSWORD 'powa';